name: hr_analytics
version: "1.0.0"
profile: hr_analytics

model-paths:
  - models

models:
  hr_analytics:
    staging:
      +materialized: view
    warehouse:
      +materialized: table
    marts:
      +materialized: table
